ComprasCartonesLGP.Web/Areas/ContentAdmin/Controllers/ImportarController.cs
using ComprasCartonesLGP.Dal;
using ComprasCartonesLGP.Entities;
using ComprasCartonesLGP.Utilities;
using ExcelDataReader;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComprasCartonesLGP.Web.Areas.ContentAdmin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ImportarController : Controller
    {
        private LGPContext db = new LGPContext();

        // GET: ContentAdmin/Importar
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ImportarLocalidades()
        {
            ViewBag.PromocionId = new SelectList(db.Promociones, "ID", "Descripcion");
            return View();
        }

        [HttpPost]
        public ActionResult ImportarLocalidades(HttpPostedFileBase file)
        {

            List<Localidades> localidades = new List<Localidades>();
            List<Alert> alerts = new List<Alert>();

            if (file.ContentLength > 0)
            {
                string extension = Path.GetExtension(file.FileName).ToLower();

                string[] validFileTypes = { ".xls", ".xlsx", ".csv" };

                string path1 = string.Format("{0}/{1}", Server.MapPath("~/Areas/ContentAdmin/Data/Uploads"), file.FileName);
                if (!Directory.Exists(path1))
                {
                    Directory.CreateDirectory(Server.MapPath("~/Areas/ContentAdmin/Data/Uploads"));
                }

                file.SaveAs(path1);

                List<string> data = new List<string>();

                using (var stream = System.IO.File.Open(path1, FileMode.Open, FileAccess.Read))
                {
                    using (var reader = ExcelReaderFactory.CreateReader(stream))
                    {
                        var result = reader.AsDataSet();
                        // Ejemplos de acceso a datos
                        DataTable table = result.Tables[0];
                        for (int i = 1; i <= (table.Rows.Count - 1); i++)
                        {
                            DataRow rows = table.Rows[i];
                            string dataRow = "";
                            for (int j = 0; j <= (table.Columns.Count - 1); j++)
                            {
                                dataRow += rows[j] + ((j != table.Columns.Count) ? ";" : "");
                            }
                            data.Add(dataRow);
                        }
                    }
                }

                foreach (var row in data)
                {
                    string[] localidadAuxiliar = row.Split(';');
                    if (localidadAuxiliar.Length == 4)
                    {
                        Localidades localidadNueva = new Localidades();
                        if (!int.TryParse(localidadAuxiliar[0].Trim(), out int ID))
                        {
                            string errorMessage = "Error en Linea: " + (data.IndexOf(row) + 2) + ", El numero de Id no es valido";
                            alerts.Add(new Alert("danger", errorMessage, true));
                            continue;
                        }

                        if (string.IsNullOrEmpty(localidadAuxiliar[1].Trim()))
                        {
                            string errorMessage = "Error en Linea: " + (data.IndexOf(row) + 2) + ", El nombre de localidad no puede estar vacio";
                            alerts.Add(new Alert("danger", errorMessage, true));
                            continue;
                        }

                        if (!int.TryParse(localidadAuxiliar[2].Trim(), out int idPcia))
                        {
                            string errorMessage = "Error en Linea: " + (data.IndexOf(row) + 2) + ", El numero de Id de provincia no es valido";
                            alerts.Add(new Alert("danger", errorMessage, true));
                            continue;
                        }

                        localidadNueva.ID = Convert.ToInt32(localidadAuxiliar[0].Trim());
                        localidadNueva.Descripcion = localidadAuxiliar[1].Trim();
                        localidadNueva.ProvinciaID = Convert.ToInt32(localidadAuxiliar[2].Trim());

                        var localidadExistente = db.Localidades.Where(x => x.ID == localidadNueva.ID).FirstOrDefault();

                        if (localidadExistente == null)
                        {
                            localidades.Add(localidadNueva);
                        }
                        else
                        {
                            if(localidadExistente.Descripcion.Trim() != localidadNueva.Descripcion)
                            {
                                localidadExistente.Descripcion = localidadNueva.Descripcion;
                                db.Entry(localidadExistente).State = EntityState.Modified;
                                db.SaveChanges();
                            }
                        }
                    }
                    else
                    {
                        string errorMessage = "Error en Linea: " + data.IndexOf(row) + ", Formato no Valido.";
                        alerts.Add(new Alert("danger", errorMessage, true));
                        continue;
                    }
                }

                if (alerts.Count == 0)
                {
                    db.Localidades.AddRange(localidades);

                    db.SaveChanges();

                    return RedirectToAction("ImportadoExitoso");
                }

                ViewBag.Alerts = alerts;
            }
            return View();

        }

        public ActionResult ImportadoExitoso()
        {
            return View();
        }
    }
}

ComprasCartonesLGP.Web/Areas/ContentAdmin/Controllers/SolicitudesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ComprasCartonesLGP.Dal;
using ComprasCartonesLGP.Entities;
using ComprasCartonesLGP.Utilities;
using ExcelDataReader;
using PagedList;

namespace ComprasCartonesLGP.Web.Areas.ContentAdmin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SolicitudesController : Controller
    {
        private LGPContext db = new LGPContext();

        // GET: ContentAdmin/Solicitudes
        public ActionResult Index(string searchString, string currentFilter, int? page)
        {
            if (!string.IsNullOrEmpty(searchString))
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.page = page;
            ViewBag.CurrentFilter = searchString;

            int pageSize = 30;
            int pageNumber = (page ?? 1);

            DateTime hoy = DateTime.Now;

            var solicitudes = db.Solicitudes.Where(x => x.Promocion.Anio == hoy.Year).ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                solicitudes = solicitudes.Where(x => x.NroSolicitud.ToUpper().Contains(searchString.ToUpper())).ToList();
            }

            return View(solicitudes.ToPagedList(pageNumber, pageSize));
        }

        // GET: ContentAdmin/Solicitudes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solicitud solicitud = db.Solicitudes.Find(id);
            if (solicitud == null)
            {
                return HttpNotFound();
            }
            return View(solicitud);
        }

        // GET: ContentAdmin/Solicitudes/Create
        public ActionResult Create()
        {
            ViewBag.PromocionId = new SelectList(db.Promociones, "ID", "Descripcion");
            return View();
        }

        // POST: ContentAdmin/Solicitudes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,PromocionId,NroSolicitud,NroCarton,Precio")] Solicitud solicitud)
        {
            if (ModelState.IsValid)
            {
                db.Solicitudes.Add(solicitud);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PromocionId = new SelectList(db.Promociones, "ID", "Descripcion", solicitud.PromocionId);
            return View(solicitud);
        }

        // GET: ContentAdmin/Solicitudes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solicitud solicitud = db.Solicitudes.Find(id);
            if (solicitud == null)
            {
                return HttpNotFound();
            }
            ViewBag.PromocionId = new SelectList(db.Promociones, "ID", "Descripcion", solicitud.PromocionId);
            return View(solicitud);
        }

        // POST: ContentAdmin/Solicitudes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,PromocionId,NroSolicitud,NroCarton,Precio")] Solicitud solicitud)
        {
            if (ModelState.IsValid)
            {
                db.Entry(solicitud).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PromocionId = new SelectList(db.Promociones, "ID", "Descripcion", solicitud.PromocionId);
            return View(solicitud);
        }

        // GET: ContentAdmin/Solicitudes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solicitud solicitud = db.Solicitudes.Find(id);
            if (solicitud == null)
            {
                return HttpNotFound();
            }

            DateTime hoy = DateTime.Now;

            var compra = (from oCompras in db.ComprasDeSolicitudes
                          join oSolicitud in db.Solicitudes on oCompras.SolicitudID equals oSolicitud.ID
                          join oPromocion in db.Promociones on oSolicitud.PromocionId equals oPromocion.ID
                          where (!oCompras.PagoCancelado &&
                                oPromocion.Anio == hoy.Year)
                                || (oCompras.PagoRealizado != 0 && oCompras.PagoCancelado)
                          select oCompras).ToList();

            var solicitudComprada = compra.Where(x => x.SolicitudID == id).FirstOrDefault();
            if(solicitudComprada != null)
            {
                return View();
            }
            return View(solicitud);
        }

        // POST: ContentAdmin/Solicitudes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Solicitud solicitud = db.Solicitudes.Find(id);
            db.Solicitudes.Remove(solicitud);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Importar()
        {
            ViewBag.PromocionId = new SelectList(db.Promociones, "ID", "Descripcion");
            return View();
        }

        [HttpPost]
        public ActionResult Importar(HttpPostedFileBase file, int? PromocionId, float Precio)
        {

            List<Solicitud> solicitudes = new List<Solicitud>();
            ViewBag.PromocionId = new SelectList(db.Promociones, "ID", "Descripcion");
            List<Alert> alerts = new List<Alert>();

            if (file.ContentLength > 0)
            {
                string extension = Path.GetExtension(file.FileName).ToLower();

                string[] validFileTypes = { ".xls", ".xlsx", ".csv" };

                string path1 = string.Format("{0}/{1}", Server.MapPath("~/Areas/ContentAdmin/Data/Uploads"), file.FileName);
                if (!Directory.Exists(path1))
                {
                    Directory.CreateDirectory(Server.MapPath("~/Areas/ContentAdmin/Data/Uploads"));
                }

                file.SaveAs(path1);

                List<string> data = new List<string>();

                using (var stream = System.IO.File.Open(path1, FileMode.Open, FileAccess.Read))
                {
                    using (var reader = ExcelReaderFactory.CreateReader(stream))
                    {
                        var result = reader.AsDataSet();
                        // Ejemplos de acceso a datos
                        DataTable table = result.Tables[0];
                        for (int i = 1; i <= (table.Rows.Count - 1); i++)
                        {
                            DataRow rows = table.Rows[i];
                            string dataRow = "";
                            for (int j = 0; j <= (table.Columns.Count - 1); j++)
                            {
                                dataRow += rows[j] + ((j != table.Columns.Count) ? ";" : "");
                            }
                            data.Add(dataRow);
                        }
                    }
                }

                foreach (var row in data)
                {
                    string[] solicitudAuxiliar = row.Split(';');
                    if (solicitudAuxiliar.Length == 2)
                    {
                        Solicitud solicitudNueva = new Solicitud();
                        if (!int.TryParse(solicitudAuxiliar[0].Trim(), out int nroSolicitud))
                        {
                            string errorMessage = "Error en Linea: " + (data.IndexOf(row) + 2 ) + ", El numero de solicitud no es valido";
                            alerts.Add(new Alert("danger", errorMessage, true));
                            continue;
                        }
                        solicitudNueva.NroSolicitud = nroSolicitud.ToString();
                        solicitudNueva.Precio = Precio;
                        solicitudNueva.PromocionId = Convert.ToInt32(PromocionId);

                        if (db.Solicitudes.Where(x => x.PromocionId == solicitudNueva.PromocionId && x.NroSolicitud == solicitudNueva.NroSolicitud).FirstOrDefault() == null)
                        {
                            solicitudes.Add(solicitudNueva);
                            //db.Solicitudes.Add(solicitudNueva);
                            //db.SaveChanges();
                        }
                    }
                    else
                    {
                        string errorMessage = "Error en Linea: " + data.IndexOf(row) + ", Formato no Valido.";
                        alerts.Add(new Alert("danger", errorMessage, true));
                        continue;
                    }
                }

                if (alerts.Count == 0)
                {
                    db.Solicitudes.AddRange(solicitudes);

                    db.SaveChanges();

ComprasCartonesLGP.Web/Areas/ContentAdmin/Views/Solicitudes/Create.cshtml
@model ComprasCartonesLGP.Entities.Solicitud
@{
    ViewBag.Title = "Solicitudes > Cargar";
}

<br />
<nav aria-label="breadcrumb">
    <ol class="breadcrumb background-turquesa3">
        <li class="breadcrumb-item textoBlanco" aria-current="page"><h4>@ViewBag.Title</h4></li>
    </ol>
</nav>
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group row">
            @Html.Label("PromocionId", "Año", htmlAttributes: new { @class = "col-sm-2 col-form-label col-form-label-sm", @for = "colFormLabelSm" })
            <div class="col-sm-6">
                @Html.DropDownList("PromocionId", null, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Precio, "Precio", htmlAttributes: new { @class = "col-sm-2 col-form-label col-form-label-sm", @for = "colFormLabelSm" })
            <div class="col-sm-6">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group row input-file">
            @Html.LabelFor(model => model., htmlAttributes: new { @class = "col-sm-2 col-form-label col-form-label-sm", @for = "colFormLabelSm" })
            <div class="input-group mb-3 col-sm-6 ">
                <div class="input-group-btn">
                    <button class="btn botonPrincipal btn-choose" type="button" id="inputGroupFileAddon03">Seleccionar</button>
                </div>
                <div class="custom-file">
                    <input type="text" multiple class="form-control custom-file" placeholder='Seleccionar archivo...' required />
                </div>
                <div>
                    <button class="btn botonPrincipal btn-reset" type="button">Limpiar Seleccion</button>
                </div>
            </div>
        </div>*@

        <div class="form-group row botones-formularios">
            <div class="margin-botones-formularios">
                <input type="submit" value="Guardar" class="btn botonPrincipal" />
            </div>
            <div class="margin-botones-formularios">
                @Html.ActionLink("Volver", "Index", null, new { @class = "btn botonPrincipal" })
            </div>
        </div>
    </div>
}

ComprasCartonesLGP.Web/Areas/ContentAdmin/Views/Solicitudes/Delete.cshtml
@model ComprasCartonesLGP.Entities.Solicitud
@{
    ViewBag.Title = "Solicitudes > Eliminar";
}

<br />
<nav aria-label="breadcrumb">
    <ol class="breadcrumb background-turquesa3">
        <li class="breadcrumb-item textoBlanco" aria-current="page"><h4>@ViewBag.Title</h4></li>
    </ol>
</nav>
<div class="page-content">
    <div id="tab-general">
        <div id="sum_box" class="row mbl">
            <div class="col-lg-12 col-sm-12 col-md-12">
                <div align="center">
                    @if (Model == null)
                    {
                        <br />
                        <div class="text-center"><h4>La solicitud no puede ser eliminada ya que ha sido adquirida por un asociado</h4></div>
                        <br /><br />
                        <p class="text-center">
                            <a href="@Url.Action("Index", new { currentFilter = @ViewBag.CurrentFilter, page = @ViewBag.page })" class="btn btn-primary">VOLVER</a>
                        </p>
                        <br />
                    }
                    else
                    {
                        using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            <h3>¿Desea realmente eliminar la solicitud seleccionada?</h3>
                            @Html.HiddenFor(model => model.ID);
                            <p>
                                <button type="submit" class="btn botonPrincipal">SÍ</button>&nbsp;&nbsp;&nbsp;<a href="@Url.Action("Index", new { currentFilter = @ViewBag.CurrentFilter, page = @ViewBag.page })" class="btn botonPrincipal">NO</a>
                            </p>
                        }
                    }
                </div>
                &nbsp;<br>
            </div>
        </div>
    </div>
</div>

ComprasCartonesLGP.Web/Areas/ContentAdmin/Views/Solicitudes/ImportadoExitoso.cshtml
@{
    ViewBag.Title = "Solicitudes > Importar";
}

<br />
<nav aria-label="breadcrumb">
    <ol class="breadcrumb background-turquesa3">
        <li class="breadcrumb-item textoBlanco" aria-current="page"><h4>@ViewBag.Title</h4></li>
    </ol>
</nav>
<div class="page-content">
    <div id="tab-general">
        <main>
            <section class="contact">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12" data-aos="fade-up" data-aos-delay="300">
                            <br />
                            <div class="text-center"><h4><strong>SOLICITUDES IMPORTADAS EXITOSAMENTE</strong></h4></div>
                            <br /><br />
                            <p class="text-center">
                                <a href="@Url.Action("Index", "Solicitudes")" class="btn btn-primary">VOLVER</a>
                            </p>
                            <br />
                        </div>
                    </div>
                </div>
            </section>
        </main>
    </div>
</div>

ComprasCartonesLGP.Web/Areas/ContentAdmin/Views/Solicitudes/Importar.cshtml
@model ComprasCartonesLGP.Entities.Solicitud
@{
    ViewBag.Title = "Solicitudes > Importar";
}

<br />
<nav aria-label="breadcrumb">
    <ol class="breadcrumb background-turquesa3">
        <li class="breadcrumb-item textoBlanco" aria-current="page"><h4>@ViewBag.Title</h4></li>
    </ol>
</nav>
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group row">
            @Html.Label("PromocionId", "Solicitudes", htmlAttributes: new { @class = "col-sm-2 col-form-label col-form-label-sm", @for = "colFormLabelSm" })
            <div class="col-sm-6">
                @Html.DropDownList("PromocionId", null, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Precio, "Precio", htmlAttributes: new { @class = "col-sm-2 col-form-label col-form-label-sm", @for = "colFormLabelSm" })
            <div class="col-sm-6">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control form-control-sm", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group row">
            <label class="col-sm-2 col-form-label col-form-label-sm" for="colFormLabelSm">Seleccione el archivo a procesar</label>
            <input class="form-control custom-file" name="file" id="file" type="file">
        </div>
        <p>
            <input type="submit" name="boton" value="PROCESAR" id="boton">
        </p>*@

        <div class="form-group row input-file">
            <label class="col-sm-2 col-form-label col-form-label-sm" for="colFormLabelSm">Archivo</label>
            <div class="input-group mb-3 col-sm-6 ">
                @*<div class="input-group-btn">
                    <button class="btn botonPrincipal btn-choose" type="button" id="inputGroupFileAddon03">Seleccionar</button>
                </div>*@
                <div class="custom-file">
                    <input type="file" name="file" id="file" multiple class="form-control custom-file" placeholder='Seleccione el archivo...' required />
                </div>
                <div>
                    <button class="btn botonPrincipal btn-reset" type="button">Limpiar Seleccion</button>
                </div>
            </div>
        </div>

        <div class="form-group row botones-formularios">
            <div class="margin-botones-formularios">
                <input type="submit" value="Guardar" class="btn botonPrincipal" />
            </div>
            <div class="margin-botones-formularios">
                @Html.ActionLink("Volver", "Index", null, new { @class = "btn botonPrincipal" })
            </div>
        </div>
    </div>
}
<div id="sum_box" class="row mbl">
    <div class="col-lg-12 col-sm-12 col-md-12">
        @if (@ViewBag.Alerts != null)
        {
            <div style="overflow-y:scroll; height:400px;">
                @foreach (var item in @ViewBag.Alerts)
                {
                    <div class="alert alert-@item.Type dismissable" role="alert" style="margin-right:5px;">
                        <span>@item.Message</span>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                }
            </div>
        }
    </div>
</div>

ComprasCartonesLGP.Web/Areas/ContentAdmin/Views/Solicitudes/Index.cshtml
@model PagedList.IPagedList<ComprasCartonesLGP.Entities.Solicitud>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Solicitudes";
}

<br />
<nav aria-label="breadcrumb">
    <ol class="breadcrumb background-turquesa3">
        <li class="breadcrumb-item textoBlanco" aria-current="page"><h4>@ViewBag.Title</h4></li>
    </ol>
</nav>
<div class="container col-md-12 row">
    <div class="col-md-4">
        <p>
            <h4>@Html.ActionLink("Cargar Solicitudes", "Importar", null, new { @class = "btn botonPrincipal" })</h4>
        </p>
    </div>
    <div class="col-md-6">
        <p></p>
        @using (Html.BeginForm())
        {
            <p>
                <strong class="">Buscar Solicitud: </strong> @Html.TextBox("searchString", ViewBag.currentFilter as string)
                <input type="submit" value="Buscar" class="btn botonPrincipal" />
            </p>
        }
    </div>
    <div class="col-md-2">
        <p>
            <h4>@Html.ActionLink("Limpiar filtro", "Index", null, new { @class = "btn botonPrincipal" })</h4>
        </p>
    </div>
</div>
<div class="table-responsive" id="tableCtaCte">
    <table class="table table-hover" id="job-table">
        <thead>
            <tr class="text-center">
                <th scope="col">
                    <div align="center">Nº Solicitud</div>
                </th>
                <th scope="col">
                    <div align="center">Precio</div>
                </th>
                <th scope="col">
                    <div align="center">Promoción</div>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody class="text-center tableBody">
            @foreach (var item in Model)
            {
                <tr class="">
                    <td class="">
                        @Html.DisplayFor(modelItem => item.NroSolicitud)
                    </td>
                    <td class="">
                        @Html.DisplayFor(modelItem => item.Precio)
                    </td>
                    <td class="">
                        @Html.DisplayFor(modelItem => item.Promocion.Anio)
                    </td>
                    <td width="5%"><a href="@Url.Action("Delete", new { id = item.ID, page = ViewBag.page, currentFilter = ViewBag.CurrentFilter })"><div align="center"><i class="fa fa-trash" aria-hidden="true"></i></div></a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="12">
                    <p></p>
                    <div align="center">
                        @Html.PagedListPager(Model, page => Url.Action("Index",
                        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                    </div>
                    <p></p>
                </td>
            </tr>
        </tfoot>
    </table>
    <br /><br />
</div>