ComprasCartonesLGP.Web/Areas/ContentAdmin/Controllers/ClientesController.cs
using ComprasCartonesLGP.Dal;
using ComprasCartonesLGP.Entities;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ComprasCartonesLGP.Web.Areas.ContentAdmin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ClientesController : Controller
    {
        private LGPContext db = new LGPContext();
        // GET: ContentAdmin/Clientes
        public ActionResult Index(string searchString, string currentFilter, int? page)
        {
            if (!string.IsNullOrEmpty(searchString))
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.page = page;
            ViewBag.CurrentFilter = searchString;

            int pageSize = 20;
            int pageNumber = (page ?? 1);

            var clientes = db.Asociados.OrderByDescending(x => x.ID).ToList();
            if (!string.IsNullOrEmpty(searchString))
            {
                clientes = clientes.Where(x => x.NombreCompleto.ToUpper().Contains(searchString.ToUpper())).ToList();
            }

            ViewBag.TotalAsociados = clientes.Count();

            return View(clientes.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Details(int? id, int? page, string currentFilter)
        {
            ViewBag.page = page;
            ViewBag.CurrentFilter = currentFilter;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asociado asociado = db.Asociados.Find(id);
            if (asociado == null)
            {
                return HttpNotFound();
            }
            if(asociado.Sexo == "1")
            {
                ViewBag.Sexo = "Femenino";
            }
            if (asociado.Sexo == "2")
            {
                ViewBag.Sexo = "Masculino";
            }
            return View(asociado);
        }
    }
}

ComprasCartonesLGP.Web/Areas/ContentAdmin/Controllers/ComprasController.cs
using ComprasCartonesLGP.Dal;
using ComprasCartonesLGP.Entities;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ComprasCartonesLGP.Web.Areas.ContentAdmin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ComprasController : Controller
    {
        private LGPContext db = new LGPContext();
        // GET: ContentAdmin/Compras
        public ActionResult Index(string searchString, string currentFilter, int? page, int Estado = 0, int Anio = 0)
        {
            ViewBag.Anio = new SelectList(db.Promociones.OrderByDescending(x => x.Anio), "Anio", "Anio");
            if (!string.IsNullOrEmpty(searchString))
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.page = page;
            ViewBag.CurrentFilter = searchString;

            int pageSize = 20;
            int pageNumber = (page ?? 1);

            if (Anio == 0)
            {
                Anio = DateTime.Now.Year;
            }

            var compras = (from oCompras in db.ComprasDeSolicitudes
                           join oSolicitud in db.Solicitudes on oCompras.SolicitudID equals oSolicitud.ID
                           join oPromocion in db.Promociones on oSolicitud.PromocionId equals oPromocion.ID
                           where oPromocion.Anio == Anio
                           select oCompras).OrderByDescending(x => x.ID).ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                compras = compras.Where(x => x.NroSolicitud.ToUpper().Contains(searchString.ToUpper())).ToList();
            }

            switch (Estado)
            {
                case 1:
                    compras = compras.Where(x => x.PagoRealizdo == true).ToList();
                    break;
                case 2:
                    compras = compras.Where(x => x.PagoRealizdo == false && x.PagoCancelado == false).ToList();
                    break;
                case 3:
                    compras = compras.Where(x => x.PagoCancelado == true).ToList();
                    break;
            }

            ViewBag.Estado = Estado;
            ViewBag.TotalCompras = compras.Count();
            return View(compras.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Details(int? id, int? page, string currentFilter, int Estado = 0, int Anio = 0)
        {
            ViewBag.page = page;
            ViewBag.CurrentFilter = currentFilter;
            ViewBag.Estado = Estado;
            ViewBag.Anio = Anio;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompraDeSolicitud compra = db.ComprasDeSolicitudes.Find(id);
            if (compra == null)
            {
                return HttpNotFound();
            }
            var asociado = db.Asociados.Where(x => x.ID == compra.AsociadoID).FirstOrDefault();
            if(compra.PagoRealizdo == true)
            {
                ViewBag.EstadoPago = "Completo";
            }
            else
            {
                if (compra.PagoCancelado == true)
                {
                    ViewBag.EstadoPago = "Anulado";
                }
                else
                {
                    ViewBag.EstadoPago = "Pendiente";
                }
            }
            var localidad = db.Localidades.Where(x => x.ID == asociado.LocalidadID).FirstOrDefault();

            ViewBag.NombreAsociado = asociado.NombreCompleto;
            ViewBag.Dni = asociado.Dni;
            ViewBag.Cuil = asociado.Cuit;
            ViewBag.FechaNacimiento = asociado.FechaNacimiento.ToString("dd-MM-yyyy");
            if(asociado.Sexo == "1")
            {
                ViewBag.Sexo = "Femenino";
            }
            if (asociado.Sexo == "2")
            {
                ViewBag.Sexo = "Masculino";
            }
            ViewBag.Calle = asociado.Direccion;
            ViewBag.Altura = asociado.Altura;
            ViewBag.Torre = asociado.Torre;
            ViewBag.Piso = asociado.Piso;
            ViewBag.Departamento = asociado.Dpto;
            ViewBag.Provincia = localidad.Provincia.Descripcion;
            ViewBag.Localidad = localidad.Descripcion;
            ViewBag.CaracTelFijo = asociado.AreaTelefonoFijo;
            ViewBag.NroTelFijo = asociado.NumeroTelefonoFijo;
            ViewBag.CaracCelu = asociado.AreaCelular;
            ViewBag.NroCelu = asociado.NumeroCelular;
            ViewBag.Email = asociado.Email;

            return View(compra);
        }

        public ActionResult TablaEstadoPago(int? id, int? page, string currentFilter, int Estado = 0, int Anio = 0)
        {
            var cuotas = db.CuotasCompraDeSolicitudes.Where(x => x.CompraDeSolicitudID == id).ToList();
            ViewBag.IdSolicitud = id;
            ViewBag.page = page;
            ViewBag.CurrentFilter = currentFilter;
            ViewBag.Estado = Estado;
            ViewBag.Anio = Anio;
            if (cuotas == null)
            {
                return HttpNotFound();
            }
            return View(cuotas);
        }
    }
}

ComprasCartonesLGP.Web/Areas/ContentAdmin/Controllers/DebitoController.cs
using ComprasCartonesLGP.Dal;
using ComprasCartonesLGP.Entities;
using ComprasCartonesLGP.Entities.Pago360.Request;
using ComprasCartonesLGP.Entities.Pago360.Response;
using ComprasCartonesLGP.Entities.ViewsModels;
using ComprasCartonesLGP.Utilities;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ComprasCartonesLGP.Web.Areas.ContentAdmin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DebitoController : Controller
    {
        private LGPContext db = new LGPContext();
        // GET: ContentAdmin/Debito
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AdheridosTarjetaCredito(string searchString, string currentFilter, int? page)
        {
            if (!string.IsNullOrEmpty(searchString))
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.page = page;
            ViewBag.CurrentFilter = searchString;

            int pageSize = 20;
            int pageNumber = (page ?? 1);
            var adheridos = db.AdhesionCard.Where(x => x.state == "signed").OrderByDescending(x => x.id).ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                adheridos = adheridos.Where(x => x.card_holder_name.ToUpper().Contains(searchString.ToUpper())).ToList();
            }

            return View(adheridos.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult AdheridosCbu(string searchString, string currentFilter, int? page)
        {
            if (!string.IsNullOrEmpty(searchString))
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.page = page;
            ViewBag.CurrentFilter = searchString;

            int pageSize = 20;
            int pageNumber = (page ?? 1);
            var adheridos = db.AdhesionCbu.Where(x => x.state == "signed").OrderByDescending(x => x.id).ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                adheridos = adheridos.Where(x => x.cbu_holder_name.ToUpper().Contains(searchString.ToUpper())).ToList();
            }

            return View(adheridos.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult ConfirmacionEnvioSolicitudDebitoCbu()
        {
            var ultimaSolicitud = db.DebitosCBU.OrderByDescending(x => x.id).FirstOrDefault();
            if (ultimaSolicitud != null)
            {
                ViewBag.UltimaSolicitud = ultimaSolicitud.created_at;
            }
            return View();
        }

        public ActionResult ConfirmacionEnvioSolicitudDebitoCard()
        {
            var ultimaSolicitud = db.DebitosCard.OrderByDescending(x => x.id).FirstOrDefault();
            if (ultimaSolicitud != null)
            {
                ViewBag.UltimaSolicitud = ultimaSolicitud.created_at;
            }
            return View();
        }

        public ActionResult DebitarCbu()
        {
            List<Alert> alerts = new List<Alert>();
            string errorMessage;

            DateTime dateTime = DateTime.Now;
            string date = dateTime.ToString("dd-MM-yyyy");
            int days = 3;
            string primerVencimiento = ObtenerDiaHabil(date, days);
            string segundoVencimiento = ObtenerDiaHabil(primerVencimiento, days);
            var adheridosCbu = db.AdhesionCbu.Where(x => x.state == "signed").ToList();
            foreach (var adherido in adheridosCbu)
            {
                //Primero valida que no se haya enviado ya una cuota este mes para este adherido
                var SolicitudEnviada = db.DebitosCBU.Where(x => x.adhesionId == adherido.id && x.created_at.Month == dateTime.Month).FirstOrDefault();
                if(SolicitudEnviada == null)
                {
                    //Busca la solicitud y valida que esta no sea nula
                    var solicitud = db.ComprasDeSolicitudes.Where(x => x.NroSolicitud == adherido.external_reference && x.PagoRealizdo == false && x.PagoCancelado == false).FirstOrDefault();
                    if (solicitud != null)
                    {
                        //Busca la cuota y valida que esta no sea nula
                        var cuotaSolicitud = db.CuotasCompraDeSolicitudes.Where(x => x.CompraDeSolicitudID == solicitud.ID && x.CuotaPagada == false).FirstOrDefault();
                        if (cuotaSolicitud != null)
                        {
                            var solicitudDebito = db.DebitosCBU.Where(x => x.CuotaId == cuotaSolicitud.ID).ToList();
                            if (solicitudDebito.Count == 0)
                            {
                                CbuDebitRequest debito = new CbuDebitRequest();
                                Metadata metadata = new Metadata();

                                debito.adhesion_id = adherido.id;
                                debito.first_due_date = primerVencimiento;
                                debito.first_total = (decimal)cuotaSolicitud.PrimerPrecioCuota;
                                debito.second_due_date = segundoVencimiento;
                                debito.second_total = (decimal)cuotaSolicitud.SeguntoPrecioCuota;
                                debito.description = "LGP. Pago cuota:  " + cuotaSolicitud.MesCuota + " a través del débito automático. Monto: $" + cuotaSolicitud.PrimerPrecioCuota;
                                metadata.external_reference = cuotaSolicitud.ID;
                                debito.metadata = metadata;

                                DebitoCBU debitoCbu = new DebitoCBU();
                                //Respuesta de la Api
                                string respuesta = "";

                                //
                                string debit360Js = JsonConvert.SerializeObject(debito);

                                //Local
                                //Uri uri = new Uri("https://localhost:44382/api/RequestDebitCbu?debitRequest=" + HttpUtility.UrlEncode(debit360Js));

                                //Server
                                Uri uri = new Uri("http://localhost:90/api/RequestDebitCbu?debitRequest=" + HttpUtility.UrlEncode(debit360Js));

                                HttpWebRequest requestFile = (HttpWebRequest)WebRequest.Create(uri);

                                requestFile.ContentType = "application/html";
                                requestFile.Headers.Add("authorization", "Bearer YjZlOTg2MWMxMzcxYTAwMDUwNmQzZWJlMWUwY2EyZWZjMzU3M2Y3NGE0ZjRkZWU0ZmRlZjcxOGQ4YmY4Yzc4ZQ");

                                HttpWebResponse webResp = requestFile.GetResponse() as HttpWebResponse;

                                if (requestFile.HaveResponse)
                                {
                                    if (webResp.StatusCode == HttpStatusCode.OK || webResp.StatusCode == HttpStatusCode.Accepted)
                                    {
                                        try
                                        {
                                            StreamReader respReader = new StreamReader(webResp.GetResponseStream(), Encoding.GetEncoding("utf-8" /*"iso-8859-1"*/));

                                            respuesta = respReader.ReadToEnd();

                                            CbuDebitResponse debitResponse = new CbuDebitResponse();
                                            //var jsonObject = JObject.Parse(response.Content);

                                            debitResponse = JsonConvert.DeserializeObject<CbuDebitResponse>(respuesta);

                                            if (debitResponse.id != 0)
                                            {
                                                debitoCbu.id = debitResponse.id;
                                                debitoCbu.type = debitResponse.type;
                                                debitoCbu.state = debitResponse.state;
                                                debitoCbu.created_at = debitResponse.created_at;
                                                debitoCbu.first_due_date = debitResponse.first_due_date;
                                                debitoCbu.first_total = debitResponse.first_total;
                                                debitoCbu.second_due_date = debito.second_due_date;
                                                debitoCbu.second_total = debitResponse.first_total;
                                                debitoCbu.description = debitResponse.description;
                                                debitoCbu.CuotaId = debitResponse.metadata.external_reference;
                                                debitoCbu.adhesionId = debitResponse.adhesion.id;

                                                db.DebitosCBU.Add(debitoCbu);
                                                db.SaveChanges();
                                            }
                                            else
                                            {
                                                var asociado = db.Asociados.Where(x => x.ID == solicitud.AsociadoID).FirstOrDefault();
                                                errorMessage = "Socio: " + asociado.NombreCompleto + ". Cuota del mes: " + cuotaSolicitud.MesCuota + ". Solicitud: " + solicitud.NroSolicitud;
                                                alerts.Add(new Alert("danger", errorMessage, true));
                                            }

                                        }
                                        catch (Exception ex)
                                        {

ComprasCartonesLGP.Web/Areas/ContentAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="La Gran Promoción" content="La Gran Promoción">
    <meta name="La Gran Promoción " content="">
    <title>La Gran Promoción</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Areas/ContentAdmin/Data/sidebar/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Areas/ContentAdmin/Data/sidebar/vendor/bootstrap/js/bootstrap.bundle.min.js" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/Areas/ContentAdmin/Data/sidebar/css/simple-sidebar.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/69d753dab5.js" crossorigin="anonymous"></script>
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/images/logo/favicon-60x60.png">
</head>
<body>
    <!--Loading-->
    <div class="loading show">
        <div class="spin"></div>
    </div>
    <div class="d-flex" id="wrapper">
        @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
        {
            @Html.AntiForgeryToken()
        }
        <!-- Sidebar -->
        <div class="bg-light background-turquesa3" id="sidebar-wrapper">
            <div class="sidebar-heading">
                <span class="logo-text textoBlanco" style="font-size:30px;"><b>ContentAdmin</b></span>
            </div>
            <hr />
            <div class="list-group list-group-flush">
                <a href="@Url.Action("Index","Home")" class="list-group-item list-group-item-action bg-light textoBlanco background-turquesa3"><b>HOME</b></a>
                <a href="@Url.Action("Index","Promociones")" class="list-group-item list-group-item-action bg-light textoBlanco background-turquesa3"><b>PROMOCIONES</b></a>
                <a href="@Url.Action("Index","Solicitudes")" class="list-group-item list-group-item-action bg-light textoBlanco background-turquesa3"><b>SOLICITUDES</b></a>
                <a href="@Url.Action("Index","Debito")" class="list-group-item list-group-item-action bg-light textoBlanco background-turquesa3"><b>DEBITOS</b></a>
                <a href="@Url.Action("Index","Compras")" class="list-group-item list-group-item-action bg-light textoBlanco background-turquesa3"><b>COMPRAS</b></a>
                <a href="@Url.Action("Index","Clientes")" class="list-group-item list-group-item-action bg-light textoBlanco background-turquesa3"><b>CLIENTES</b></a>
                <a href="@Url.Action("HabilitarCompra","Home")" class="list-group-item list-group-item-action bg-light textoBlanco background-turquesa3"><b>HABILITAR COMPRA</b></a>
                <a href="@Url.Action("Index","Exportar")" class="list-group-item list-group-item-action bg-light textoBlanco background-turquesa3"><b>EXPORTAR</b></a>
                <a href="@Url.Action("Index","Importar")" class="list-group-item list-group-item-action bg-light textoBlanco background-turquesa3"><b>IMPORTAR</b></a>
                <a href="javascript:document.getElementById('logoutForm').submit()" class="list-group-item list-group-item-action bg-light textoBlanco background-turquesa3"><b>CERRAR SESIÓN</b></a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-dark bg-light border-bottom background-turquesa4">
                <button class="btn btn-default" id="menu-toggle">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </nav>
            <div class="container-fluid">
                @RenderBody()
                <div id="footer">
                    <div class="col-sm-12 text-right textoBlanco">
                        <p class="text-right">Desarrollado y Hosteado por <a href="http://stnt.com.ar/" style="color: black" target="_blank"><b>StartNet</b></a></p>
                    </div>
                </div>

            </div>
        </div>
        <!-- Copyright -->
        <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->
</body>
</html>
<!-- Bootstrap core JavaScript -->
<script src="~/Areas/ContentAdmin/Data/sidebar/vendor/jquery/jquery.min.js"></script>
<script src="~/Areas/ContentAdmin/Data/sidebar/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<!-- Menu Toggle Script -->
<script>
    var Loading = (loadingDelayHidden = 0) => {
        // Variables
        //-----------------------------------------------------
        // HTML
        let loading = null;
        // Retardo para borrar
        const myLoadingDelayHidden = loadingDelayHidden;

        /**
         * Ocultar HTML
         */
        function hideLoading() {
            // Comprueba que exista el HTML
            if (loading !== null) {
                // Oculta el HTML de "cargando..." quitando la clase .show
                loading.classList.remove('show');
                // Borra el HTML
                setTimeout(function () {
                    loading.remove();
                }, myLoadingDelayHidden);
            }

        }

        /**
         * Método que inicia la lógica
         */
        function init() {
            /* Comprobar que el HTML esté cargadas */
            document.addEventListener('DOMContentLoaded', function () {
                loading = document.querySelector('.loading');
                hideLoading();
            });
        }

        return {
            'init': init
        }
    }

    //Para usarlo se declara e inicia. El número es el tiempo transcurrido para borra el HTML una vez cargado todos los elementos, en este caso 1 segundo: 1000 milisegundos,
    Loading(500).init();

    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>